# docker build -f Dockerfile_diffdock_cpu -t mrbrandonwalker/diffdock_cpu .

FROM condaforge/mambaforge

# need rsync to copy cached files to speedup diffdock execution see
# https://github.com/gcorso/DiffDock/blob/main/README.md?plain=1#L65
RUN apt-get update && apt-get install -y wget git build-essential rsync

RUN conda install pytorch==1.13.0 cpuonly -c pytorch

# Using torch 1.13 to be as consistent as possible with gpu DiffDock image
# Need to install pytorch first before other torch packages
# Cannot use conda for these packages otherwise will install them with a default CUDA (not same as cuda 11.7)
# so need to specify which package versions (CUDA and Torch)

RUN pip install torch-scatter torch-sparse torch-cluster torch-spline-conv torch-geometric==2.0.4 -f https://data.pyg.org/whl/torch-1.12.0+cpu.html

RUN conda install PyYAML scipy "networkx[default]" biopython rdkit e3nn spyrmsd pandas biopandas

# still need this package for importing despite documentation on github saying only needed for GPU implementation
RUN pip install "fair-esm[esmfold]"

RUN git clone https://github.com/gcorso/DiffDock.git

WORKDIR /DiffDock

RUN conda init bash

RUN python -m inference --protein_ligand_csv data/protein_ligand_example_csv.csv --out_dir results/user_predictions_small --inference_steps 1 --samples_per_complex 1 --batch_size 1 --actual_steps 1

RUN rm -r results/user_predictions_small

RUN mamba clean --all --yes

RUN pip cache purge

RUN apt-get clean